#!/bin/bash
set -e -x
echo "Setting up gimme"
mkdir ~/bin
curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
chmod +x ~/bin/gimme
gimme 1.4.2
cat >>.profile <<"_EOF_"
. /home/vagrant/.gimme/envs/go1.4.2.env
_EOF_

# lets test this ish
. ~/.profile
echo "Configured go: $(go version)"

echo "Installing godep"
go get github.com/tools/godep
echo "Godep installed"
